<a href="https://colab.research.google.com/github/Puneetrai004/100-Days-of-Machine-Learning/blob/main/Ordinal_Encoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [48]:
import numpy as np
import pandas as pd

In [49]:
df = pd.read_csv('customer.csv')

In [51]:
df.sample(5)

age  gender   review education purchased
40   39    Male     Good    School        No
0    30  Female  Average    School        No
5    31  Female  Average    School       Yes
23   96  Female     Good    School        No
25   57  Female     Good    School        No

In [52]:
df = df.iloc[:,2:] # gender is nominal, age is numerical, Review & education is ordinal, Purchased(Y) is Nominal
#Needs Column transformer

In [73]:
df.head(15)

review education purchased
0   Average    School        No
1      Poor        UG        No
2      Good        PG        No
3      Good        PG        No
4   Average        UG        No
5   Average    School       Yes
6      Good    School        No
7      Poor    School       Yes
8   Average        UG        No
9      Good        UG       Yes
10     Good        UG       Yes
11     Good        UG       Yes
12     Poor    School        No
13  Average    School        No
14     Poor        PG       Yes

In [54]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,0:2],df.iloc[:,-1])

In [55]:
X_train

review education
46     Poor        PG
30  Average        UG
40     Good    School
21  Average        PG
17     Poor        UG
14     Poor        PG
9      Good        UG
42     Good        PG
27     Poor        PG
6      Good    School
23     Good    School
16     Poor        UG
10     Good        UG
8   Average        UG
19     Poor        PG
18     Good    School
36     Good        UG
28     Poor    School
26     Poor        PG
2      Good        PG
43     Poor        PG
22     Poor        PG
49     Good        UG
3      Good        PG
1      Poor        UG
25     Good    School
34  Average    School
32  Average        UG
11     Good        UG
45     Poor        PG
38     Good    School
47     Good        PG
15     Poor        UG
48     Good        UG
31     Poor    School
33     Good        PG
5   Average    School

In [56]:
from sklearn.preprocessing import OrdinalEncoder

In [57]:
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

In [58]:
oe.fit(X_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [59]:
X_train = oe.transform(X_train)
X_test = oe.transform(X_test)

In [60]:
X_train

array([[0., 2.],
       [1., 1.],
       [2., 0.],
       [1., 2.],
       [0., 1.],
       [0., 2.],
       [2., 1.],
       [2., 2.],
       [0., 2.],
       [2., 0.],
       [2., 0.],
       [0., 1.],
       [2., 1.],
       [1., 1.],
       [0., 2.],
       [2., 0.],
       [2., 1.],
       [0., 0.],
       [0., 2.],
       [2., 2.],
       [0., 2.],
       [0., 2.],
       [2., 1.],
       [2., 2.],
       [0., 1.],
       [2., 0.],
       [1., 0.],
       [1., 1.],
       [2., 1.],
       [0., 2.],
       [2., 0.],
       [2., 2.],
       [0., 1.],
       [2., 1.],
       [0., 0.],
       [2., 2.],
       [1., 0.]])

In [64]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [65]:
X_train

array([[0., 2.],
       [1., 1.],
       [2., 0.],
       [1., 2.],
       [0., 1.],
       [0., 2.],
       [2., 1.],
       [2., 2.],
       [0., 2.],
       [2., 0.],
       [2., 0.],
       [0., 1.],
       [2., 1.],
       [1., 1.],
       [0., 2.],
       [2., 0.],
       [2., 1.],
       [0., 0.],
       [0., 2.],
       [2., 2.],
       [0., 2.],
       [0., 2.],
       [2., 1.],
       [2., 2.],
       [0., 1.],
       [2., 0.],
       [1., 0.],
       [1., 1.],
       [2., 1.],
       [0., 2.],
       [2., 0.],
       [2., 2.],
       [0., 1.],
       [2., 1.],
       [0., 0.],
       [2., 2.],
       [1., 0.]])

In [67]:
from sklearn.preprocessing import LabelEncoder

In [68]:
le = LabelEncoder()

In [69]:
le.fit(y_train)

LabelEncoder()

In [70]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [71]:
y_train = le.transform(y_train)
y_test = le.transform(y_test)

In [72]:
y_train

array([0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1])